"""
LogGuardian AI Database Module.
Handles schema initialization, scan storage, metrics aggregation,
history search, and deletion of records.
"""

import os
import sqlite3
import json
from datetime import datetime
from typing import Dict, Any, List, Tuple, Optional
from config import DATABASE_PATH
from logger import log

def get_db_connection() -> sqlite3.Connection:
    """Creates and returns a connection to the SQLite database."""
    # Ensure database folder exists
    db_dir = os.path.dirname(DATABASE_PATH)
    os.makedirs(db_dir, exist_ok=True)
    
    conn = sqlite3.connect(DATABASE_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db() -> None:
    """Initializes the database schema if tables do not exist."""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # 1. Scans Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS scans (
            id TEXT PRIMARY KEY,
            timestamp TEXT NOT NULL,
            filename TEXT NOT NULL,
            file_size INTEGER NOT NULL,
            log_type TEXT NOT NULL,
            security_score INTEGER NOT NULL,
            risk_rating TEXT NOT NULL,
            total_entries INTEGER NOT NULL,
            total_alerts INTEGER NOT NULL,
            ai_summary TEXT
        )
    """)
    
    # 2. Alerts Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            scan_id TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            source_ip TEXT,
            username TEXT,
            detector TEXT NOT NULL,
            severity TEXT NOT NULL,
            description TEXT NOT NULL,
            tactic TEXT,
            technique_id TEXT,
            technique_name TEXT,
            payload TEXT,
            FOREIGN KEY (scan_id) REFERENCES scans (id) ON DELETE CASCADE
        )
    """)
    
    # 3. Normalized Logs Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS normalized_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            scan_id TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            source_ip TEXT,
            username TEXT,
            method TEXT,
            uri TEXT,
            status_code INTEGER,
            response_size INTEGER,
            user_agent TEXT,
            raw_line TEXT,
            FOREIGN KEY (scan_id) REFERENCES scans (id) ON DELETE CASCADE
        )
    """)
    
    # Create indexes for search performance
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_alerts_scan_id ON alerts(scan_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_alerts_ip ON alerts(source_ip)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_logs_scan_id ON normalized_logs(scan_id)")
    
    conn.commit()
    conn.close()
    log.info("Database initialized successfully.")

def save_scan(scan_id: str,
              filename: str,
              file_size: int,
              log_type: str,
              security_score: int,
              risk_rating: str,
              total_entries: int,
              alerts: List[Dict[str, Any]],
              normalized_entries: List[Dict[str, Any]],
              ai_summary: str) -> None:
    """
    Saves a completed scan run, its detected alerts, and normalized entries to database.
    
    Args:
        scan_id: UUID of the scan.
        filename: Log file name.
        file_size: Log file size in bytes.
        log_type: Type of logs processed (e.g., Nginx, SSH).
        security_score: 0-100 system security score.
        risk_rating: Calculated risk string.
        total_entries: Total logs processed.
        alerts: List of alert dicts.
        normalized_entries: List of parsed log entries.
        ai_summary: Markdown string generated by the threat analyzer.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    try:
        # Save scan header
        timestamp = datetime.now().isoformat()
        cursor.execute("""
            INSERT INTO scans (id, timestamp, filename, file_size, log_type, security_score, risk_rating, total_entries, total_alerts, ai_summary)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (scan_id, timestamp, filename, file_size, log_type, security_score, risk_rating, total_entries, len(alerts), ai_summary))
        
        # Save alerts (up to a reasonable limit to prevent database bloat)
        for alert in alerts:
            cursor.execute("""
                INSERT INTO alerts (scan_id, timestamp, source_ip, username, detector, severity, description, tactic, technique_id, technique_name, payload)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                scan_id,
                alert.get("timestamp", timestamp),
                alert.get("source_ip"),
                alert.get("username"),
                alert.get("detector"),
                alert.get("severity", "MEDIUM"),
                alert.get("description", ""),
                alert.get("tactic"),
                alert.get("technique_id"),
                alert.get("technique_name"),
                alert.get("payload")
            ))
            
        # Save normalized entries (limit to first 5000 lines to avoid excessive storage)
        for entry in normalized_entries[:5000]:
            cursor.execute("""
                INSERT INTO normalized_logs (scan_id, timestamp, source_ip, username, method, uri, status_code, response_size, user_agent, raw_line)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                scan_id,
                entry.get("timestamp", timestamp),
                entry.get("source_ip"),
                entry.get("username"),
                entry.get("method"),
                entry.get("uri"),
                entry.get("status_code"),
                entry.get("response_size"),
                entry.get("user_agent"),
                entry.get("raw_line", "")
            ))
            
        conn.commit()
        log.info(f"Scan '{scan_id}' successfully saved to SQLite database. Alerts: {len(alerts)}")
    except Exception as e:
        conn.rollback()
        log.error(f"Error saving scan to database: {e}")
        raise e
    finally:
        conn.close()

def get_all_scans(limit: int = 50, offset: int = 0, search_query: Optional[str] = None) -> List[Dict[str, Any]]:
    """Retrieves list of scans from history."""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    if search_query:
        query = f"%{search_query}%"
        cursor.execute("""
            SELECT * FROM scans 
            WHERE filename LIKE ? OR log_type LIKE ? OR risk_rating LIKE ?
            ORDER BY timestamp DESC LIMIT ? OFFSET ?
        """, (query, query, query, limit, offset))
    else:
        cursor.execute("SELECT * FROM scans ORDER BY timestamp DESC LIMIT ? OFFSET ?", (limit, offset))
        
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

def get_scan(scan_id: str) -> Optional[Dict[str, Any]]:
    """Retrieves a single scan by ID."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM scans WHERE id = ?", (scan_id,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None

def get_scan_alerts(scan_id: str) -> List[Dict[str, Any]]:
    """Retrieves all alerts belonging to a specific scan."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM alerts WHERE scan_id = ? ORDER BY timestamp ASC", (scan_id,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

def get_scan_logs(scan_id: str, limit: int = 1000) -> List[Dict[str, Any]]:
    """Retrieves logs stored in the scan."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM normalized_logs WHERE scan_id = ? ORDER BY timestamp ASC LIMIT ?", (scan_id, limit))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

def delete_scan(scan_id: str) -> bool:
    """Deletes a scan and its cascaded logs/alerts."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("PRAGMA foreign_keys = ON")  # Ensure cascade deletion happens
        cursor.execute("DELETE FROM scans WHERE id = ?", (scan_id,))
        conn.commit()
        log.info(f"Scan {scan_id} deleted successfully.")
        return True
    except Exception as e:
        conn.rollback()
        log.error(f"Failed to delete scan: {e}")
        return False
    finally:
        conn.close()

def get_scan_metrics(scan_id: str) -> Dict[str, Any]:
    """
    Computes breakdown metrics of alerts for a specific scan.
    
    Returns:
        A dictionary containing severity chart stats, attack type stats, and top IPs.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    metrics: Dict[str, Any] = {}
    
    # 1. Severity Distribution
    cursor.execute("""
        SELECT severity, COUNT(*) as count 
        FROM alerts WHERE scan_id = ? 
        GROUP BY severity
    """, (scan_id,))
    metrics["severities"] = {row["severity"]: row["count"] for row in cursor.fetchall()}
    
    # 2. Attack Category / Detector Distribution
    cursor.execute("""
        SELECT detector, COUNT(*) as count 
        FROM alerts WHERE scan_id = ? 
        GROUP BY detector
    """, (scan_id,))
    metrics["detectors"] = {row["detector"]: row["count"] for row in cursor.fetchall()}
    
    # 3. Top Attacking IPs
    cursor.execute("""
        SELECT source_ip, COUNT(*) as count 
        FROM alerts WHERE scan_id = ? AND source_ip IS NOT NULL AND source_ip != ''
        GROUP BY source_ip ORDER BY count DESC LIMIT 5
    """, (scan_id,))
    metrics["top_ips"] = [{"ip": row["source_ip"], "count": row["count"]} for row in cursor.fetchall()]
    
    # 4. Top Targeted Users
    cursor.execute("""
        SELECT username, COUNT(*) as count 
        FROM alerts WHERE scan_id = ? AND username IS NOT NULL AND username != ''
        GROUP BY username ORDER BY count DESC LIMIT 5
    """, (scan_id,))
    metrics["top_users"] = [{"username": row["username"], "count": row["count"]} for row in cursor.fetchall()]

    # 5. Timeline data
    cursor.execute("""
        SELECT timestamp, severity, detector, source_ip 
        FROM alerts WHERE scan_id = ? 
        ORDER BY timestamp ASC
    """, (scan_id,))
    metrics["timeline"] = [dict(r) for r in cursor.fetchall()]
    
    conn.close()
    return metrics

def get_global_metrics() -> Dict[str, Any]:
    """Computes global platform-wide statistics for the dashboard homepage."""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    metrics: Dict[str, Any] = {
        "total_scans": 0,
        "total_alerts": 0,
        "total_logs": 0,
        "avg_security_score": 100.0,
        "alerts_by_severity": {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "CRITICAL": 0},
        "scans_by_type": {}
    }
    
    try:
        # Total counts
        cursor.execute("SELECT COUNT(*) as count FROM scans")
        metrics["total_scans"] = cursor.fetchone()["count"]
        
        cursor.execute("SELECT SUM(total_alerts) as count FROM scans")
        sum_alerts = cursor.fetchone()["count"]
        metrics["total_alerts"] = sum_alerts if sum_alerts else 0
        
        cursor.execute("SELECT SUM(total_entries) as count FROM scans")
        sum_logs = cursor.fetchone()["count"]
        metrics["total_logs"] = sum_logs if sum_logs else 0
        
        # Average Security Score
        cursor.execute("SELECT AVG(security_score) as avg_score FROM scans")
        avg = cursor.fetchone()["avg_score"]
        metrics["avg_security_score"] = round(avg, 1) if avg is not None else 100.0
        
        # Severity breakdown
        cursor.execute("SELECT severity, COUNT(*) as count FROM alerts GROUP BY severity")
        for row in cursor.fetchall():
            metrics["alerts_by_severity"][row["severity"]] = row["count"]
            
        # Log type distribution
        cursor.execute("SELECT log_type, COUNT(*) as count FROM scans GROUP BY log_type")
        for row in cursor.fetchall():
            metrics["scans_by_type"][row["log_type"]] = row["count"]
            
    except Exception as e:
        log.error(f"Error computing global database metrics: {e}")
    finally:
        conn.close()
        
    return metrics
